version: '2'
services:
    cids-integration-base:
      image: cismet/cids-integration-base:latest
      container_name: switchon_cids-integration-base
      ports:
        - "5434:5432"
      volumes:
        - cids-integration-base:/cidsIntegrationBase/pg_data
        - ~/switchon-docker-volumes/switchon/cids-integration-base/import/:/import/cidsIntegrationBase/
      command: [start, import]
    cids-server:
      image: cismet/cids-server:latest
      container_name: switchon_cids-server:latest
      links:
        - "cids-integration-base:cids-integration-base"
      depends_on: 
        - cids-integration-base
      ports:
        - "9986:9986"
      environment:
        - LOG4J_HOST=172.17.0.1
        - CIDS_ACCOUNT_EXTENSION=Switchon
        - CIDS_SERVER_STARTER=cids-custom-switchon-server-4.0-starter.jar
        # Environment variables are no longer the recommended method for connecting to linked services. 
        # Instead, you should use the link name (by default, the name of the linked service) as the hostname to connect to. 
        # See the docker-compose.yml documentation for details.
        # Environment variables will only be populated if you’re using the legacy version 1 Compose file format.
        - CIDS_INTEGRATION_BASE_PORT_5432_TCP_ADDR=cids-integration-base
        - CIDS_INTEGRATION_BASE_PORT_5432_TCP_PORT=5432
      volumes:
        - cids-server:/cidsDistribution
        - ~/switchon-docker-volumes/switchon/cids-server/import/:/import/cids-server/
    cids-server-rest-legacy:
      image: cismet/cids-server-rest-legacy:latest
      container_name: switchon_cids-cids-server-rest-legacy
      links:
        - "cids-server:cids-server"
      depends_on: 
        - cids-server
      ports:
        - "8890:8890"
      environment:
        - LOG4J_HOST=172.17.0.1
        - CIDS_ACCOUNT_EXTENSION=Switchon
        - CIDS_SERVER_PORT_9986_TCP_ADDR=cids-server
        - CIDS_SERVER_PORT_9986_TCP_PORT=9986
      volumes_from:
        - cids-server
      volumes:
        - ~/switchon-docker-volumes/switchon/cids-server-rest-legacy/import/:/import/cids-server-rest-legacy/
volumes:
  cids-integration-base:
    driver: local
  cids-server:
    driver: local
  cids-server-rest-legacy:
    driver: local