version: '2'
services:
    cids-integration-base:
      image: cismet/cids-integration-base:postgres-9.6.1
      container_name: cidsdistributionswitchon_cids-integration-base
      ports:
        - "5434:5432"
      volumes:
        - cids-integration-base:/data
        - ~/docker-volumes-switchon/cids-distribution-switchon/cids-integration-base/import/:/import/cids-integration-base/
volumes:
  cids-integration-base:
    driver: local